### ISSUE TITLE
check-static does not seem to work

### ISSUE THREAD

**Issue by ramal-ratne** [unbit/uwsgi#1305]
Hello,

We are serving PHP with a NGINX fronted via Fastgi. 

The static file index.html raises an error 

```
PHP security error: /var/app/public/index.html does not end with an allowed extension
```

However, the `check-static = %(project_dir)` is correctly set as follows.  

Please note - When `php-allowed-ext` is removed it works.

How can I fix this so that the Fastcgi container here serves both PHP and static content? 

Thanks

```
[uwsgi]
; load the required plugins, php is loaded as the default (0) modifier
plugins-dir = /usr/lib/uwsgi/
; bind the http router to port 80
fastcgi-socket = :8888
pidfile = /tmp/uwsgi-pid
fastcgi-modifier1 = 14
fastcgi-modifier2 = 2

php-sapi-name = apache
plugins = php

; our working dir (the DOCUMENT_ROOT of our instance)
project_dir = /var/app/public

; chdir to it (just for fun)
chdir = %(project_dir)

; check for static files in it
; check for static files in it
check-static = %(project_dir)
; ...but skip .php and .inc extensions
static-skip-ext = .php
static-skip-ext = .inc

; search for index.html when a dir is requested
static-index = index.html

; jail our php environment to project_dir
php-docroot = %(project_dir)

; ... and to the .php and .inc extensions
php-allowed-ext = .php
php-allowed-ext = .inc

; and search for index.php and index.inc if required
php-index = index.php
php-index = index.inc

; set php timezone
php-set = date.timezone=Europe/Rome

; use a max of 10 processes
processes = 10
; ...but start with only 2 and spawn the others on demand
cheaper = 2
```

**Comment by digitalfiz** [comment]
This was closed did you ever actually figure it out?

**Comment by jchv** [comment]
I was stuck on this problem and it comes up on Google, so hopefully this comment will help someone some day.

The problem is that `static-skip-ext` doesn't work as expected for some reason. It looks like the INI parser is doing something weird with values that start with `.` and I haven't figured out why. I also do not have the faintest of clues why it isn't affecting the `php-allowed-ext` option.

You can do
```
static-skip-ext = php
```

but then all filenames ending in "php" will 403 because they will hit the `php-allowed-ext` restriction. You could also pass the option via command line, which as far as I can tell, works, but it's ugly.

But honestly, here's what you actually should do: use YAML-based configuration instead. Even if the INI problem is easily solved, INI is very defacto and there's a lot of different INI-like formats that all act differently. 

```yaml
uwsgi:
    plugins: "http,0:php"
    http: ":80"
    master: true
    master-as-root: true
    uid: "www-data"
    gid: "www-data"
    log-5xx: true
    workers: 2
    max-requests: 2048

    project-dir: "/var/www/"
    chdir: "%(project-dir)"
    check-static: "%(project-dir)"
    static-skip-ext: ".php"
    static-index: "index.html"

    php-docroot: "%(project-dir)"
    php-allowed-ext: ".php"
    php-index: "index.php"
    php-sapi-name: apache
```
