### ISSUE TITLE
Race condition graceful restart while fork master

### ISSUE THREAD

**Issue by gmoryes** [unbit/uwsgi#1492]
Hello, I'm using fork master ("f") scheme of restart, writing here: http://zarnovican.github.io/2016/02/15/uwsgi-graceful-reload/#re-exec-master-r_1

Here my yaml file:
```
uwsgi:
  socket: 0.0.0.0:2809
  psgi: /path/to/file.psgi
  master:  true
#  processes: 4
  coroae: 1000
  need-app:  true
  log-reopen:  yes 
  worker-reload-mercy: 10800
  vacuum: false                                     # see below for explanation
  master-fifo: /path/to/new/instance.fifo
  master-fifo: /path/to/running/instance.fifo


  if-exists: /path/to/running/instance.fifo
  hook-accepting1-once: writefifo:/path/to/running/instance.fifo q
  endif: 
#race condition point
  hook-accepting1-once: writefifo:/path/to/new/instance.fifo 1P
```
After #race_condition_point there is 2 ways:
1) the old master receive 'q' and delete and create fifo-file, after that new master delete and create fifo-file and change master-fifo to 1
2) the new master delete and create fifo file, change master-fifo to 1 and **after** this **old** master delete and create fifo file (because we send 'q' him)

so the good case is 1)
but if the 2) happened, so the old process continue listen fifo file, and after it's death nobody listen fifo file => so we can't do "echo f > /path/to/running/instance.fifo", so to restart service we must kill process and start it again

Is the usage of this yaml is deprecated or it is bug of uwsgi?
