### ISSUE TITLE
uWSGI with libyaml: static-map parsing

### ISSUE THREAD

**Issue by almahmoud** [unbit/uwsgi#2097]
We are running uWSGI with libyaml, accomplished by specifying a profile as mentioned in: https://github.com/unbit/uwsgi/issues/863#issuecomment-240605936, and after much debugging found that the YAML configuration has some oddly specific requirements when it comes to listing `static-map` entries.
Specifically, the following configuration does not work:
```
uwsgi:
  static-map:
  - /static/style=/server/static/style/blue
  - /static=/server/static
  - /favicon.ico=/server/static/favicon.ico
```
appearing as if there is no static mapping, although it is technically valid YAML, but the following does work:
```
uwsgi:
  static-map:
    - /static/style=/server/static/style/blue
    - /static=/server/static
    - /favicon.ico=/server/static/favicon.ico
```
Additionally, we noticed that all the keys after `static-map` are inexplicably ignored.
Specifically, the following will properly parse all the configs:
```
uwsgi:
  buffer-size: 16384
  die-on-term: true
  enable-threads: true
  hook-master-start: 'unix_signal:2 gracefully_kill_them_all'
  http: 0.0.0.0:8080
  manage-script-name: true
  master: true
  offload-threads: 2
  processes: 1
  py-call-osafterfork: true
  threads: 4
  thunder-lock: true
  static-map:
    - /static/style=/server/static/style/blue
    - /static=/server/static
    - /favicon.ico=/server/static/favicon.ico
```
but, if the `static-map` is specified earlier in the config, everything after it seems to be ignored. For example, this will result in uWSGI signaling that thunder lock is disabled:
```
uwsgi:
  buffer-size: 16384
  die-on-term: true
  enable-threads: true
  hook-master-start: 'unix_signal:2 gracefully_kill_them_all'
  http: 0.0.0.0:8080
  manage-script-name: true
  master: true
  offload-threads: 2
  processes: 1
  py-call-osafterfork: true
  threads: 4
  static-map:
    - /static/style=/server/static/style/blue
    - /static=/server/static
    - /favicon.ico=/server/static/favicon.ico
  thunder-lock: true
```

This is specifically affecting us because we want to use valid YAML (so duplicate keys are problematic, hence the need for the libyaml version) and are generating the YAML config file through the Helm templating engine (ultimately running in a Kubernetes environment), and thus do not have direct control over the order of the keys or the indentation unless we special case the key which we are trying to avoid doing. Our presumption was that since it is libyaml, it should be able to parse any valid YAML config file, but that seems to not be the case. Are we missing something?
