### ISSUE TITLE
cheaper config not working propery with YAML-based config

### ISSUE THREAD

**Issue by albertodonato** [unbit/uwsgi#2098]
I've been using a `.ini` config as the following, with the cheaper busyness algo:

```ini
[uwsgi]
...
cheaper = 4
cheaper-algo = busyness
cheaper = 4
cheaper-initial = 4
cheaper-overload = 1
cheaper-step = 4
cheaper-busyness-multiplier = 60
cheaper-busyness-min = 30
cheaper-busyness-max = 60
cheaper-busyness-backlog-alert = 16
cheaper-busyness-backlog-step = 2
...
workers = 50
```

I now wanted to switch to configure uWSGI with YAML, and came up with the following config:

```yaml
uwsgi:
  ...
  cheaper: 4
  cheaper-algo: busyness
  cheaper-busyness-backlog-alert: 16
  cheaper-busyness-backlog-step: 2
  cheaper-busyness-max: 60
  cheaper-busyness-min: 30
  cheaper-busyness-multiplier: 60
  cheaper-initial: 4
  cheaper-overload: 1
  cheaper-step: 4
  ...
  workers: 50
```

When running uWSGI with the latter, I get the following error: `"invalid cheaper value: must be lower than processes"`

**Comment by awelzel** [comment]
Hey @albertodonato ,

does the `...` in your config contain a list/nested structure? You may just be seeing  #2097 .

Concretely, the following config (besides `env` not being recognized) will yield the same error message because everything following `env` is ignored :-(
```
uwsgi:
  http-socket: ':4040'
  cheaper: 4
  wsgi: tests.hello
  static-map: /static/js=/server/static/js
  static-map: /static/css=/server/static/css
  env:
    - ENVIRONMENT=prod
  workers: 50

invalid cheaper value: must be lower than processes
```

If you have control over it, you may be able to move `workers` up.

**Comment by albertodonato** [comment]
hi @awelzel,

no, my config is flat, no lists or nested structures.

It does seem to be an issue with ordering because `cheaper` is defined before `workers`. Unfortunately I don't have control over the config output as it's generated and keys are sorted alphabetically, but order shouldn't really matter in the yaml.

**Comment by awelzel** [comment]
> no, my config is flat, no lists or nested structures.

Okay - it just seemed likely. Unfortunately I'm not able to reproduce with the following config:
```
uwsgi:
  http-socket: :4040
  wsgi: tests.simple
  cheaper: 4
  cheaper-algo: busyness
  cheaper-busyness-backlog-alert: 16
  cheaper-busyness-backlog-step: 2
  cheaper-busyness-max: 60
  cheaper-busyness-min: 30
  cheaper-busyness-multiplier: 60
  cheaper-initial: 4
  cheaper-overload: 1
  cheaper-step: 4
  workers: 50
```

Do you have a minimal reproducer?
