### ISSUE TITLE
How to make heavy-load-proof system using AWS Fargate and uWSGI without max-requests-delta options

### ISSUE THREAD

**Issue by masalennon** [unbit/uwsgi#2235]
Hello everyone, I really need your help.
I'm using uWSGI behind Nginx to run a Flask application on Fargate.

`uWSGI listen queue of socket ":9090" (fd: 3) full !!! `

I've been experiencing the above error during load-testing. It seems this is happening when uWSGI's proccesses are restarting. (while restarting, queue of socket gets full by incoming requests)
As it is not possible to change the maximum number of queue of sockets on Fargate, I really need a way to prevent uWSGI from respawning its processes at once.
Does anyone have a good idea to make it work?
I came up with setting random value for max-worker-lifetime, but it couldn't solve this issue completely.

A totally different approach to make heavy-loading-proof system of uWSGI + Nginx + Flask on Fargate is also welcomed.

Here is my setting.

```Dockerfile
CMD ["uwsgi", "--yaml", "/etc/uwsgi/uwsgi.yml", \
              "--max-worker-lifetime", "`awk -v min=1800 -v max=5400 'BEGIN{srand(); print int(min+rand()*(max-min+1))}'`" ]
```

```yaml
uwsgi:
  http-socket: :9090
  strict: true
  pidfile: /tmp/uwsgi.pid
  chdir: /dir
  module: api:app
  uid: root
  gid: root
  thunder-lock: true
  vacuum: true
  harakiri: 60
  listen: 128
  http-keepalive: 1
  master: 1
  workers: 50
  enable-threads: true

  disable-logging: true
  log-4xx: true
  log-5xx: true
```

**Comment by unbit** [comment]
@masalennon maybe chain reloading is the right approach for you: https://uwsgi.readthedocs.io/en/latest/articles/TheArtOfGracefulReloading.html#chain-reloading-lazy-apps

**Comment by masalennon** [comment]
Thank you! Should I use other options such as max-requests or max-worker-lifetime options to specify when worker restart?

**Comment by masalennon** [comment]
now my uwsgi.yml and Dockerfile look like below:
```yaml
  lazy-apps: true
  touch-chain-reload: true
  master-fifo: /tmp/fifo
```

```Dockerfile
RUN echo c > /tmp/fifo

EXPOSE 9090
CMD ["uwsgi", "--yaml", "/etc/uwsgi/uwsgi.yml"]
```

`upstream prematurely closed connection while reading response header from upstream`

but now I have been getting the error above...

Need further investigation.
