### ISSUE TITLE
uwsgi_run_command() attempts to close enormous number of sockets, causing 100% CPU

### ISSUE THREAD

**Issue by paulej** [unbit/uwsgi#2698]
I have an application that starts via docker-compose. It had been working well for months, but I updated to Fedora 41 and it started causing the CPU to peg to 100%.

I tracked the problem down to this line of code: https://github.com/unbit/uwsgi/blob/master/core/utils.c#L2542.

The value used there was 1073741816.  I tried to find where it was being assigned, and it appears to be here: https://github.com/unbit/uwsgi/blob/master/core/uwsgi.c#L2776.

I was able to solve the issue by adding a constraint to the docker-compose file as follows:

```yaml
    ulimits:                                                                                                            
      nofile:                                                                                                           
        soft: 1024                                                                                                      
        hard: 2048
```

That seemed to tame things. I don't know what docker used to allow as resource limits, but I guess they are enormous now. I did not change any configuration regarding docker. So, whatever change just happened with the Fedora 41 upgrade.

While this might be a docker issue (or a Fedora issue), I think it's probably best to not attempt to close 1073741816 sockets, even if the OS says you can.
