### ISSUE TITLE
Can not get mountpoint when start.

### ISSUE THREAD

**Issue by linnchord** [unbit/uwsgi#321]
Today, I update our site uwsgi server to 1.9.12, then got 
`mountpoint  already configured. skip.` 
log in every request. 

Because the server can not get the right mountpoint from nginx conf SERVER_NAME

```
(mountpoint='') ready in 0 seconds on interpreter 0x7f82a8c09b30 pid: 47864 (default app) 
```

I check the doc of config option "vhost"
http://uwsgi-docs.readthedocs.org/en/latest/Options.html#vhost

It's still there.

Why I can not get the right param?

I try multiple version of uwsgi 1.9+, 1.9.12~1.9.7 get nothing, 1.9.5 make the host:port string to be mountpoint.

```
mountpoint='127.0.0.1:8280|'
```

That's ok to run, but not elegant.

**How I can make the right thing?**

my nginx conf

```
server{
    listen 8000;
    charset utf-8;
    server_name localhost 127.0.0.1;
    root /Volumes/Home/linnchord/www/test;

    location / {
    include uwsgi_params;
        uwsgi_pass unix:/var/run/uwsgi/socket;
        uwsgi_param UWSGI_CHDIR /Volumes/Home/linnchord/www/test;
        uwsgi_param UWSGI_SCRIPT test;
        uwsgi_param SERVER_NAME test;
    }
}

server{
    listen 8280;
    charset utf-8;
    server_name localhost 127.0.0.1;
    root /Volumes/Home/linnchord/www/gift/giftpi_web;

    location / {
    include uwsgi_params;
        uwsgi_pass unix:/var/run/uwsgi/socket;
        uwsgi_param UWSGI_CHDIR /Volumes/Home/linnchord/www/gift/giftpi_web;
        uwsgi_param UWSGI_SCRIPT giftpi;
        uwsgi_param SERVER_NAME giftpi;
    }
}
```

uwsgi.yaml

```
uwsgi:
    socket: /var/run/uwsgi/socket
    master: 1
    workers: 4
    logdate: 1
    chmod-socket: 666
    limit-as: 256
    harakiri: 60
    max-requests: 500
    touch-reload: /var/tmp/uwsgi/reload.uwsgi
    vhost: 1
    daemonize: /var/log/uwsgi/uwsgi.log
    home: /Volumes/Home/linnchord/pyenv/my/
    disable-logging: 1
    py-auto-reload: 1
    callable: app
```

env

```
nginx 1.4.1 -> 1.2
mac + brew 
ubuntu(online server)
```

THANKS!
