### ISSUE TITLE
vassal doesn't get kill when stop emperor

### ISSUE THREAD

**Issue by favadi** [unbit/uwsgi#733]
I'm running openerp with uwsgi 2.07 in emperor mode.

For testing purpose, I have to stop and uninstall uwsgi many times a day. And sometimes, the openerp-master and worker processes still appear in the process list, openerp-master process's ppid is 1.

The uwsgi build config:

``` yaml
[uwsgi]
xml = false
ini = false
yaml = true
json = false
sqlite3 = false
zeromq = false
snmp = false
spooler = true
embedded = true
ssl = false
udp = true
multicast = false
threading = true
minterpreters = true
matheval = false
async = true
ldap = false
pcre = false
routing = false
alarm = false
ipv6 = false
debug = false
unbit = false
syslog = true
xml_implementation = libxml2
yaml_implementation = auto
malloc_implementation = libc
extras =
plugins =
bin_name = uwsgi
append_version =
plugin_dir = .
embedded_plugins = python,syslog, gevent, ping, nagios, carbon, signal
as_shared_library = false
locking = auto
event = auto
timer = auto
filemonitor = auto
blacklist =
whitelist =
embed_files =
embed_config =
```

The emperor config:

``` yaml
uwsgi:
  threaded-logger: True
  logger: syslog:uwsgi
  carbon-id: emperor
  carbon: mycompany.com:2014
  emperor: /etc/uwsgi
  no-orphans: True
  die-on-term: True
```

The openerp config:

``` yaml
uwsgi:
  master: true
  processes: 2
  harakiri: 60
  harakiri-verbose: true
  lazy-apps: true
  uid: openerp
  gid: openerp
  procname: openerp-worker
  procname-master: openerp-master
  socket: /var/lib/uwsgi/openerp.sock
  stats: /var/lib/uwsgi/openerp-stats.sock
  chdir: /usr/local/openerp/openerp-7.0-20130909-231057/openerp
  wsgi-file: /usr/local/openerp/openerp-7.0-20130909-231057/openerp.wsgi
  virtualenv: /usr/local/openerp
  threaded-logger: true
  no-orphans: true
  logger: syslog:uwsgi-openerp
  carbon-id: openerp
  carbon: 107.170.94.182:2003
  chmod-socket: 770
  chown-socket: www-data:www-data
```

I can't create a test to reliable reproduce the problem. It's kind of happens randomly, sometimes it happens very often and sometimes I simply can't make make it happens.

Does anyone has this problem before? How can I prevent it? Right now I have to run `pkill -9 -f [o]penerp-master` after uninstall uwsgi to make sure the process die.
