### ISSUE TITLE
yaml config: unclear how to specifiy repeating options

### ISSUE THREAD

**Issue by ovanes** [unbit/uwsgi#863]
I started to migrate our ini-file configs to yaml files. In our ini file we have multiple environment variables specified, i.e.

```
[uwsgi]
...

env=DB_HOST=whateverhost
env=SEARCH_SERVER=whateverserver
...
```

Now I am stuck, with the migration to enviroment variables to yaml. I tried the following possibilities, which do not work:

```
uwsgi:
   ...
   env:
      - DB_HOST=whateverhost
      - SEARCH_SERVER=whateverserver
```

or 

```
uwsgi:
   ...
   env:
      DB_HOST: whateverhost
      SEARCH_SERVER: whateverserver
```

Any suggestions are very welcome :) And may be dock updates...

**Comment by unbit** [comment]
with the embedded parser (the 'dumb' one) you can just pass multiple keys:

```yaml
uwsgi:
    env: KEY1=VAL1
    env: KEY2=VAL2
```

while with libyaml-based parsers you need to pass them as sequence:

```yaml
uwsgi:
    env:
        - KEY1=VAL1
        - KEY2=VAL2
```
